### ISSUE TITLE
problem with postgresql

### ISSUE THREAD

**Issue by jave** [tkock/owncloud-docker-compose#2]
postgres_1 | The files belonging to this database system will be owned by user "postgres".
postgres_1 | This user must also own the server process.
postgres_1 | 
postgres_1 | The database cluster will be initialized with locale "en_US.utf8".
postgres_1 | The default database encoding has accordingly been set to "UTF8".
postgres_1 | The default text search configuration will be set to "english".
postgres_1 | 
postgres_1 | Data page checksums are disabled.
postgres_1 | 
postgres_1 | initdb: directory "/var/lib/postgresql/data" exists but is not empty
postgres_1 | It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
postgres_1 | Using a mount point directly as the data directory is not recommended.
postgres_1 | Create a subdirectory under the mount point.
ownclouddockercompose_postgres_1 exited with code 1

**Comment by tkock** [comment]
`postgres_1 | initdb: directory "/var/lib/postgresql/data" exists but is not empty
postgres_1 | It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.`
please remove the .gitignore file in the /var/lib/postgresql/data directory. It ends up there in order to preserve the (empty) directory in the repo.

**Comment by jave** [comment]
thanks. Maybe the rights.sh script could fix this up?

**Comment by tkock** [comment]
Thanks for the suggestion, I have updated the rights script accordingly.
